FROM almalinux:9
#CMD ["ping","google.com"]  # we can Overwrite domain ()
# continusly running untin you break
#ENTRYPOINT ["ping" , "google.com"] 
CMD ["google.com"]
ENTRYPOINT ["ping"] 


# docker run ent:v1 <anydomain it will ping>