# image searching time usefull we have 1000s of images same as almalinux
FROM almalinux:9
LABEL COURSE="DevOps" \
      TRAINER="Sivakumar" \
      DURATION="120HRS" \
      com.joindevops.dockerfile.author="siva@joindevops.com"